// lib/creations.ts
//
// Source unique des données pour la page Créations.
// app/creations/page.tsx importe ce fichier et se contente de l'afficher —
// ajouter/modifier une pièce se fait uniquement ici, jamais dans page.tsx.

export type Category = "vetement" | "accessoire";

export type Creation = {
    slug: string;
    cat: Category;
    title: string;
    meta?: string; // type vêt/access si pas dans title
    desc: string;
    size?: string; // vêt = OK, access = NOK
    price: string;
    badge: string; // disponibilité
    cardImage: { src: string; alt: string };
    modalImages: { src: string; alt: string }[];
};

const V = "/images/creations/vetements";
const A = "/images/creations/accessoires";

// ============================================================
// VÊTEMENTS (22 pièces)
// ============================================================

const vetements: Creation[] = [
    {
        slug: "bi-pull",
        cat: "vetement",
        title: "Artisane - 127,70 €",
        meta: "Pull",
        desc: "Sweat rouge.\nCoton/viscose écru ligné rouge.",
        size: "Taille 38",
        price: "Matières = 17,70 €.\nModèle = 110 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/biPull.jpg`, alt: "Bi-Pull, porté" },
        modalImages: [
            { src: `${V}/buste/biPullB.jpg`, alt: "Bi-Pull, sur buste" },
            { src: `${V}/model/biPull.jpg`, alt: "Bi-Pull, porté" }],
    },
    {
        slug: "byzance-01",
        cat: "vetement",
        title: "Byzance Grey - 281,50 €",
        meta: "Veste",
        desc: "Fausse fourrure ligné blanc/gris.\nFausse fourrure gris ardoise.\nDoublure satinée beige.",
        size: "Taille 38/40",
        price: "Matières = 86,50 €.\nModèle = 195 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/byzance01.jpg`, alt: "Byzance Grey, porté" },
        modalImages: [
            { src: `${V}/buste/byzance01B.jpg`, alt: "Byzance Grey, sur buste" },
            { src: `${V}/model/byzance01.jpg`, alt: "Byzance Grey, porté" },
            { src: `${V}/model/byzance01Dos.jpg`, alt: "Byzance Grey, dos, porté" }],
    },
    {
        slug: "byzance-02",
        cat: "vetement",
        title: "Byzance Red - 255 €",
        meta: "Veste",
        desc: "Fausse fourrure écrue double face quadrillée rouge.\nFausse fourrure girs/brun.",
        size: "Taille 38/40",
        price: "Modèle = 195 €.\nMatières = 60 €.",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/byzance02.jpg`, alt: "Byzance Red, porté" },
        modalImages: [
            { src: `${V}/buste/byzance02B.jpg`, alt: "Byzance Red, sur buste" },
            { src: `${V}/model/byzance02.jpg`, alt: "Byzance Red, porté" },
            { src: `${V}/model/byzance02Dos.jpg`, alt: "Byzance Red, dos, porté" }
        ],
    },
    {
        slug: "byzance-03",
        cat: "vetement",
        title: "Byzance White - 275 €",
        meta: "Veste",
        desc: "Fausse fourrue écrue tachetée.\nFausse fourrure écrue.",
        size: "Taille 38/40",
        price: "Modèle = 195 €.\nMatières = 80 €.",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/byzance03.jpg`, alt: "Byzance White, porté" },
        modalImages: [
            { src: `${V}/buste/byzance03B.jpg`, alt: "Byzance White, sur buste" },
            { src: `${V}/model/byzance03.jpg`, alt: "Byzance White, porté" },
            { src: `${V}/model/byzance03Dos.jpg`, alt: "Byzance White, dos, porté" }
        ],
    },
    {
        slug: "cape-reverse",
        cat: "vetement",
        title: "Cape - 210 €",
        meta: "Réversible",
        desc: "Col en fausse fourrure\nLaine quadrillée blanc et bleu clair.\nLaine bleu nuit avec fil doré.\nBoutons dorés et bleu nuit.",
        size: "Taille 38/40",
        price: "Modèle = 130 €.\nMatières = 80 €.",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/capeA01.jpg`, alt: "Cape face A open, porté" },
        modalImages: [
            { src: `${V}/buste/capeA01B.jpg`, alt: "Cape face A open, sur buste" },
            { src: `${V}/buste/capeA02B.jpg`, alt: "Cape face A close, sur buste" },
            { src: `${V}/buste/capeB01B.jpg`, alt: "Cape face B open, sur buste" },
            { src: `${V}/buste/capeB02B.jpg`, alt: "Cape face B close, sur buste" },
            { src: `${V}/model/capeA01.jpg`, alt: "Cape face A open, porté" },
            { src: `${V}/model/capeA02.jpg`, alt: "Cape face A fermé, porté" },
            { src: `${V}/model/capeB01.jpg`, alt: "Cape face B open, porté" },
            { src: `${V}/model/capeB02.jpg`, alt: "Cape face B fermmé, porté" }
        ],
    },
    {
        slug: "capette-01",
        cat: "vetement",
        title: "Dôme Blue - 127 €",
        meta: "Capette",
        desc: "Laine chevron bleu/écru.\nGalon.",
        size: "Taille 38",
        price: "Modèle = 85 €.\nMatières = 42 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/capette01.jpg`, alt: "Capette SD Blue, portée" },
        modalImages: [
            { src: `${V}/buste/capette01B.jpg`, alt: "Capette SD Blue, sur buste" },
            { src: `${V}/model/capette01.jpg`, alt: "Capette SD Blue, portée" }],
    },
    {
        slug: "capette-02",
        cat: "vetement",
        title: "Dôme White/Grey - 115 €",
        meta: "Capette",
        desc: "Laine bouclette lignée gris/écru.",
        size: "Taille 38",
        price: "Modèle = 85 €.\nMatières = 30 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/capette02.jpg`, alt: "Capette SD White/Grey, portée" },
        modalImages: [
            { src: `${V}/buste/capette02B.jpg`, alt: "Capette SD White/Grey, sur buste" },
            { src: `${V}/model/capette02.jpg`, alt: "Capette SD White/Grey, portée" }],
    },
    {
        slug: "decape-01",
        cat: "vetement",
        title: "Décape Fur Ecru - 138,75 €",
        meta: "Cape",
        desc: "Fausse fourrure écrue tachetée.\nFausse fourrure écrue.\nDoublue ardoise satinée.",
        size: "Taille 38",
        price: "Modèle = 100 €.\nMatoères = 38,75 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/cape01.jpg`, alt: "Décape Fur Ecru, portée" },
        modalImages: [
            { src: `${V}/buste/cape01B.jpg`, alt: "Décape Fur Ecru, sur buste" },
            { src: `${V}/model/cape01.jpg`, alt: "Décape Fur Ecru, portée" }],
    },
    {
        slug: "decape-02",
        cat: "vetement",
        title: "Décape Red - 141,50 €",
        meta: "Cape",
        desc: "Laine bouclette rouge.\nLainage fin rouge.\nDoublure ardoise satinée.",
        size: "Taille 38",
        price: "Modèle = 100 €.\nMatières = 41,50 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/cape02.jpg`, alt: "Décape Red, portée" },
        modalImages: [
            { src: `${V}/buste/cape02B.jpg`, alt: "Décape Red, sur buste" },
            { src: `${V}/model/cape02.jpg`, alt: "Décape Red, portée" }],
    },
    {
        slug: "decape-03",
        cat: "vetement",
        title: "Décape Minkee Ecru - 127 €",
        meta: "Cape",
        desc: "Minkee écru.\nMaille à peluchons blanc.",
        size: "Taille 38",
        price: "Modèle = 100 €.\nMatières = 27 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/cape03.jpg`, alt: "Décape Minkee Ecru, portée" },
        modalImages: [{ src: `${V}/model/cape03.jpg`, alt: "Décape Minkee Ecru, portée" }],
    },
    {
        slug: "fakecoat",
        cat: "vetement",
        title: "Fake Coat - 379,40 €",
        meta: "Robe",
        desc: "Tartan rouge.\nVoile noir.\nDoublure noire.",
        size: "Taille 38",
        price: "Modèle = 320 €.\nMatières = 59,40 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/robeFakeCoat.jpg`, alt: "Robe Fake Coat, porté" },
        modalImages: [
            { src: `${V}/buste/robeFakeCoatB.jpg`, alt: "Robe Fake Coat, sur buste" },
            { src: `${V}/model/robeFakeCoat.jpg`, alt: "Robe Fake Coat, porté" },
            { src: `${V}/model/robeFakeCoatDos.jpg`, alt: "Robe Fake Coat, dos, porté" }
        ],
    },
    {
        slug: "openlegs",
        cat: "vetement",
        title: "OpenLegs - 304,85 €",
        meta: "Manteau",
        desc: "Vinyle noir.\nDoublure jacquard satinée beige.",
        size: "Taille 38",
        price: "Modèle = 250 €.\nMatières = 54,85 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/openLegs.jpg`, alt: "OpenLegs, portée" },
        modalImages: [
            { src: `${V}/buste/openVesteB.jpg`, alt: "OpenLegs, sur buste" },
            { src: `${V}/model/openLegs.jpg`, alt: "OpenLegs, portée" },
            { src: `${V}/model/openLegsDos.jpg`, alt: "OpenLegs, dos, porté" }
        ],
    },
    {
        slug: "pant-corset",
        cat: "vetement",
        title: "Corsetier - 133,75 €",
        meta: "Pantalon",
        desc: "Jersey noir.\nPolyester élasthane - carreaux coloré",
        size: "Taille 38/40",
        price: "Modèle = 90 €.\nMatières = 43,75 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/pantCorset.jpg`, alt: "Pantalon Corset, porté" },
        modalImages: [
            { src: `${V}/buste/pantCorsetB.jpg`, alt: "Pantalon Corset, sur buste" },
            { src: `${V}/model/pantCorset.jpg`, alt: "Pantalon Corset, porté" },
            { src: `${V}/model/pantCorsetDos.jpg`, alt: "Pantalon Corset, dos, porté" }
        ],
    },
    {
        slug: "pant-valy",
        cat: "vetement",
        title: "Valy/Duel - 192,80 €",
        meta: "Pantalon",
        desc: "Simili cuir noir.\nVoile rouge pourpre",
        size: "Taille 38",
        price: "Modèle = 140 €.\nMatières = 52,80 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/pantValy.jpg`, alt: "Pantalon Valy, porté" },
        modalImages: [
            { src: `${V}/buste/pantValyB.jpg`, alt: "Pantalon Valy, sur buste" },
            { src: `${V}/model/pantValy.jpg`, alt: "Pantalon Valy, porté" }],
    },
    {
        slug: "reverse-01",
        cat: "vetement",
        title: "Maille de 2 - 192 €",
        meta: "Réversible",
        desc: "Maille impriméjacquard.",
        size: "Taille 38/40",
        price: "Modèle = 150 €.\nMatières = 42 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/reverse01.jpg`, alt: "Pull Réversible I, porté" },
        modalImages: [
            { src: `${V}/buste/pulRev01.jpg`, alt: "Maille de 2 I, sur buste" },
            { src: `${V}/buste/pulRev02.jpg`, alt: "Maille de 2 II, sur buste" },
            { src: `${V}/model/reverse01.jpg`, alt: "Maille de 2 I, porté" },
            { src: `${V}/model/reverse02.jpg`, alt: "Maille de 2 II, porté" },
            { src: `${V}/model/pullReverse01Dos.jpg`, alt: "Maille de 2 I, dos, porté" },
            { src: `${V}/model/pullReverse02Dos.jpg`, alt: "Maille de 2 II, dos,  porté" }],
    },
    {
        slug: "top-01",
        cat: "vetement",
        title: "KMiSol Grey - 115 €",
        meta: "Top",
        desc: "Voile de polyester gris/mauve, quadrillage floqué noir.",
        size: "Taille 38",
        price: "Modèle = 100 €.\nMatières = 15 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/top01.jpg`, alt: "Top I, porté" },
        modalImages: [
            { src: `${V}/buste/top01B.jpg`, alt: "Top KMiSol Grey, sur buste" },
            { src: `${V}/model/top01.jpg`, alt: "Top KMiSol Grey, porté" }],
    },
    {
        slug: "top-02",
        cat: "vetement",
        title: "KMiSol Red - 115€",
        meta: "Top",
        desc: "Polyester satiné rouge, tacheté noit/écru..",
        size: "Taille 38",
        price: "Modèle = 100 €.\nMatières = 15 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/top02.jpg`, alt: "Top KMiSol Red, porté" },
        modalImages: [
            { src: `${V}/buste/top02B.jpg`, alt: "Top KMiSol Red, sur buste" },
            { src: `${V}/model/top02.jpg`, alt: "Top KMiSol Red, porté" }],
    },
    {
        slug: "top-03",
        cat: "vetement",
        title: "KMiSol Green - 115 €",
        meta: "Top",
        desc: "Polyester satiné vert, tacheté noir/écru.",
        size: "Taille 38",
        price: "Modèle = 100 €.\nMatières = 15 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/top03.jpg`, alt: "Top KMiSol Green, porté" },
        modalImages: [
            { src: `${V}/buste/top03B.jpg`, alt: "Top KMiSol Green, sur buste" },
            { src: `${V}/model/top03.jpg`, alt: "Top KMiSol Green, porté" }],
    },
    {
        slug: "top-04",
        cat: "vetement",
        title: "KMiSol Black/Yellow/Gold - 115 €",
        meta: "Top",
        desc: "Viscose fond blanc, tacheté noir/jaune/or.",
        size: "Taille 38",
        price: "Modèle = 100 €.\nMatières = 15 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/top04.jpg`, alt: "Top KMiSol Black/Yellow/Gold, porté" },
        modalImages: [
            { src: `${V}/buste/top04B.jpg`, alt: "Top KMiSol Black/Yellow/Gold, sur buste" },
            { src: `${V}/model/top04.jpg`, alt: "Top KMiSol Black/Yellow/Gold, porté" }],
    },
    {
        slug: "tri-jupe",
        cat: "vetement",
        title: "Pan de 3 - 268 €",
        meta: "Jupe",
        desc: "Suédine crème.\nCrèpe blanc.\nVoile bordeaux - motif fleurs et or",
        size: "Taille 38",
        price: "Modèle = 220 €.\nMatières = 48 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/triJupe.jpg`, alt: "Tri-Jupe, portée" },
        modalImages: [
            { src: `${V}/buste/triJupeB.jpg`, alt: "Tri-Jupe, sur buste" },
            { src: `${V}/model/triJupe.jpg`, alt: "Tri-Jupe, portée" },
            { src: `${V}/model/triJupeDos.jpg`, alt: "Tri-Jupe, dos, portée" }
        ],
    },
    {
        slug: "veste-chine",
        cat: "vetement",
        title: "Pavillon Chine - 309,40 €",
        meta: "Veste",
        desc: "Fausse fourrure gris ardoise.\nCoton écru.\nDoublure noire.",
        size: "Taille 38",
        price: "Modèle = 220 €.\nMatières = 89,40 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/vesteChine.jpg`, alt: "Veste Chine, portée" },
        modalImages: [
            { src: `${V}/buste/vesteChineB.jpg`, alt: "Veste Chine, sur buste" },
            { src: `${V}/model/vesteChine.jpg`, alt: "Veste Chine, portée" },
            { src: `${V}/model/vesteChineDos.jpg`, alt: "Veste Chine, dos, portée" }
        ],
    },
    {
        slug: "veste-dc",
        cat: "vetement",
        title: "Emprise - 280,50 €",
        meta: "Manteau",
        desc: "Fausse fourrure crème.\nDoublure noire.\nTissu texturé noir.",
        size: "Taille 38",
        price: "Modèle = 215 €.\nMatières = 65,50 €",
        badge: "Sur commande",
        cardImage: { src: `${V}/model/vesteDC.jpg`, alt: "Veste DC, portée" },
        modalImages: [
            { src: `${V}/buste/VesteDCB.jpg`, alt: "Veste DC, sur buste" },
            { src: `${V}/model/vesteDC.jpg`, alt: "Veste DC, portée" },
            { src: `${V}/model/vesteDCDos.jpg`, alt: "Veste DC, dos, portée" }
        ],
    },
];

// ============================================================
// ACCESSOIRES (22 modèles)
// ============================================================

const accessoires: Creation[] = [
    {
        slug: "baroudeur-militaire",
        cat: "accessoire",
        title: "Baroudeur Militaire",
        meta: "Chèche",
        desc: "Variation kaki du chèche, ambiance utilitaire et graphique.",
        price: "Modèle = 35 €.\nMatières = 10-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/baroudeurMilitaire.jpg`, alt: "Chèche Baroudeur Militaire" },
        modalImages: [{ src: `${A}/baroudeurMilitaire.jpg`, alt: "Chèche Baroudeur Militaire" }],
    },
    {
        slug: "baroudeur-noir",
        cat: "accessoire",
        title: "Baroudeur Noir",
        meta: "Chèche",
        desc: "Châle enveloppant à motif torsadé, pensé pour un usage cocooning autant qu'élégant.",
        price: "Modèle = 35 €.\nMatières = 10-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/baroudeurNoir.jpg`, alt: "Chèche Baroudeur Noir" },
        modalImages: [{ src: `${A}/baroudeurNoir.jpg`, alt: "Chèche Baroudeur Noir" }],
    },
    {
        slug: "boheme-retro",
        cat: "accessoire",
        title: "Bohème Rétro",
        meta: "Châle avec galons",
        desc: "Châle enveloppant à motif torsadé, pensé pour un usage cocooning autant qu'élégant.",
        price: "Modèle = 30 €.\nMatières = 10-20 €",
        badge: "Disponible",
        cardImage: { src: `${A}/bohemeRetro.jpg`, alt: "Châle Bohème Rétro" },
        modalImages: [{ src: `${A}/bohemeRetro.jpg`, alt: "Châle Bohème Rétro" }],
    },
    {
        slug: "col-hiver",
        cat: "accessoire",
        title: "Couche d'Hiver",
        meta: "Col",
        desc: "Écharpe tubulaire en fausse fourrure, chaude et texturée, pour twister une tenue simple.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/colHiver.jpg`, alt: "Mini col Fourrure" },
        modalImages: [{ src: `${A}/colHiver.jpg`, alt: "Mini col Fourrure" }],
    },
    {
        slug: "col-pointe",
        cat: "accessoire",
        title: "Tour Pointé",
        meta: "Col",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 35 €.\nMatières = 10-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/colPointe01.jpg`, alt: "Col Pointe, face" },
        modalImages: [
            { src: `${A}/colPointe02.jpg`, alt: "Col Pointe, profil" },
            { src: `${A}/colPointe01.jpg`, alt: "Col Pointe, face" },
        ],
    },
    {
        slug: "double-snood-01",
        cat: "accessoire",
        title: "Cocon Poly",
        meta: "Double Snood",
        desc: "À compléter.",
        price: "Modèle = 35 €.\nMatières = 10-25 €",
        badge: "Sur Commande",
        cardImage: { src: `${A}/doubleSnood01.jpg`, alt: "Cocon Poly, Double Snood 01" },
        modalImages: [{ src: `${A}/doubleSnood01.jpg`, alt: "Cocon Poly, Double Snood 01" }],
    },
    {
        slug: "double-snood-02",
        cat: "accessoire",
        title: "Cocon Velvet",
        meta: "Double Snood",
        desc: "À compléter.",
        price: "Modèle = 35 €.\nMatières = 10-25 €",
        badge: "Sur Commande",
        cardImage: { src: `${A}/doubleSnood02.jpg`, alt: "Cocon Velvet, Double Snood 02" },
        modalImages: [{ src: `${A}/doubleSnood02.jpg`, alt: "Cocon Velvet, Double Snood 02" }],
    },
    {
        slug: "double-snood-03",
        cat: "accessoire",
        title: "Cocon Torsade",
        meta: "Double Snood",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 35 €.\nMatières = 10-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/doubleSnood03.jpg`, alt: "Cocon Torsade, Double Snood 03" },
        modalImages: [{ src: `${A}/doubleSnood03.jpg`, alt: "Cocon Torsade, Double Snood 03" }],
    },
    {
        slug: "metamorphe",
        cat: "accessoire",
        title: "Métamorphe",
        meta: "Châle",
        desc: "À compléter.",
        price: "Modèle = 30 €.\nMatières = 15-25 €",
        badge: "Sur Commande",
        cardImage: { src: `${A}/metamorphe01.jpg`, alt: "Métamorphe, bi-châle" },
        modalImages: [
            { src: `${A}/metamorphe01.jpg`, alt: "Métamorphe, bi-Châle angle 1" },
            { src: `${A}/metamorphe02.jpg`, alt: "Métamorphe, bi-Châle angle 2" },
            { src: `${A}/metamorphe03.jpg`, alt: "Métamorphe, Bi-Châle angle 3" },
        ],
    },
    {
        slug: "multiforme-orange",
        cat: "accessoire",
        title: "Multiforme Orange",
        meta: "Écharpe — Multi fonction",
        desc: "À compléter.",
        price: "Modèle = 50 €.\nMatières = 20-40 €",
        badge: "Sur Commande",
        cardImage: { src: `${A}/multiformeOrange01.jpg`, alt: "Écharpe Multiforme Orange" },
        modalImages: [
            { src: `${A}/multiformeOrange01.jpg`, alt: "Écharpe Multiforme Orange, version 1" },
            { src: `${A}/multiformeOrange02.jpg`, alt: "Écharpe Multiforme Orange, version 2" },
            { src: `${A}/multiformeOrange03.jpg`, alt: "Écharpe Multiforme Orange, version 3" },
        ],
    },
    {
        slug: "multiforme-rouge",
        cat: "accessoire",
        title: "Multiforme Rouge",
        meta: "Écharpe — Multi fonction",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 50 €.\nMatières = 20-40 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/multiformeRouge01.jpg`, alt: "Écharpe Multiforme Rouge" },
        modalImages: [
            { src: `${A}/multiformeRouge01.jpg`, alt: "Écharpe Multiforme Rouge, version 1" },
            { src: `${A}/multiformeRouge02.jpg`, alt: "Écharpe Multiforme Rouge, version 2" },
            { src: `${A}/multiformeRouge03.jpg`, alt: "Écharpe Multiforme Rouge, version 3" },
        ],
    },
    {
        slug: "nomade",
        cat: "accessoire",
        title: "Nomade",
        meta: "Col capuche",
        desc: "Capuche enveloppante en maille grise, portée seule ou par-dessus une veste.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/nomade.jpg`, alt: "Capuche Nomade" },
        modalImages: [{ src: `${A}/nomade.jpg`, alt: "Capuche Nomade" }],
    },
    {
        slug: "panier-lingette",
        cat: "accessoire",
        title: "Panier Lingette",
        meta: "6 lingettes par panier",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 30 €.\nMatières = 5-15 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/panierLingettes.jpg`, alt: "Lingettes, version Panier" },
        modalImages: [
            { src: `${A}/croissantLingettes.jpg`, alt: "Lingettes, version Croissant" },
            { src: `${A}/mosaiqueLingettes.jpg`, alt: "Lingettes, version Mosaique" },
            { src: `${A}/panierLingettes.jpg`, alt: "Lingettes, version Panier" }],
    },
    {
        slug: "parisienne",
        cat: "accessoire",
        title: "Parisienne",
        meta: "Écharpe",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 40 €.\nMatières = 15-25 €",
        badge: "A DETERMINER", // ???
        cardImage: { src: `${A}/parisienne.jpg`, alt: "Parisienne, Écharpe coupe structurée" },
        modalImages: [{ src: `${A}/parisienne.jpg`, alt: "Parisienne, Écharpe coupe structurée" }],
    },
    {
        slug: "patchwork-urbain",
        cat: "accessoire",
        title: "Patchwork Urbain",
        meta: "Écharpe",
        desc: "Écharpe rayée à trois teintes, tissée à la main, pièce graphique et chaude.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "A DETERMINER", // ???
        cardImage: { src: `${A}/patchworkUrbain.jpg`, alt: "Écharpe Patchwork Urbain" },
        modalImages: [{ src: `${A}/patchworkUrbain.jpg`, alt: "Écharpe Patchwork Urbain" }],
    },
    {
        slug: "snood-cream",
        cat: "accessoire",
        title: "Combo Cream",
        meta: "Snood",
        desc: "À compléter.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "A DETERMINER", // ???
        cardImage: { src: `${A}/snoodCream.jpg`, alt: "Snood Crème Nath" },
        modalImages: [{ src: `${A}/snoodCream.jpg`, alt: "Snood Crème Nath" }],
    },
    {
        slug: "snood-01",
        cat: "accessoire",
        title: "Semi Cocon Torsade",
        meta: "Snood",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/snood01.jpg`, alt: "Snood" },
        modalImages: [{ src: `${A}/snood01.jpg`, alt: "Snood" }],
    },
    {
        slug: "sphinx",
        cat: "accessoire",
        title: "Sphinx",
        meta: "Écharpe Capuche",
        desc: "Capuche prolongée en écharpe, deux accessoires réunis en une seule pièce continue.",
        price: "Modèle = 35 €.\nMatières = 15-30 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/sphinx.jpg`, alt: "Écharpe Capuche Sphinx" },
        modalImages: [{ src: `${A}/sphinx.jpg`, alt: "Écharpe Capuche Sphinx" }],
    },
    {
        slug: "tdc-01",
        cat: "accessoire",
        title: "Tubul Red",
        meta: "Tour de cou",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 30 €.\nMatières = 10-20 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/tdc01.jpg`, alt: "Tour de Cou Red" },
        modalImages: [{ src: `${A}/tdc01.jpg`, alt: "Tour de Cou Red" }],
    },
    {
        slug: "tdc-02",
        cat: "accessoire",
        title: "Tubul Brown",
        meta: "Tour de cou",
        desc: "À compléter — décris cette pièce ici.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "Sur commande",
        cardImage: { src: `${A}/tdc02.jpg`, alt: "Tour de Cou Brun" },
        modalImages: [{ src: `${A}/tdc02.jpg`, alt: "Tour de Cou Brun" }],
    },
    {
        slug: "toteBagMiroir-chien",
        cat: "accessoire",
        title: "Miroir Bulldog",
        meta: "Tote Bag",
        desc: "À compléter — Sac réversible.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "Sur Commande",
        cardImage: { src: `${A}/chiensB.jpg`, alt: "Sac Bulldog" },
        modalImages: [
            { src: `${A}/chiens.jpg`, alt: "Sac Bulldog sur buste" },
            { src: `${A}/chiensB.jpg`, alt: "Sac Bulldog, à plat" },
        ],
    },
    {
        slug: "toteBagMiroir-chat",
        cat: "accessoire",
        title: "Miroir Chat",
        meta: "Tote Bag",
        desc: "À compléter — Sac réversible.",
        price: "Modèle = 35 €.\nMatières = 15-25 €",
        badge: "Sur Commande",
        cardImage: { src: `${A}/chatsB.jpg`, alt: "Sac Chat" },
        modalImages: [
            { src: `${A}/chats.jpg`, alt: "Sac Chat sur buste" },
            { src: `${A}/chatsB.jpg`, alt: "Sac Chat, à plat" },
        ],
    },
];

export const creations: Creation[] = [...vetements, ...accessoires];